name = "Vela"
uuid = "e20ed1ff-b155-4b65-a650-1609b657a8ad"
authors = ["Abhimanyu Susobhanan <abhisrkckl@gmail.com>"]
version = "0.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
