name: docs-CI
on:
    push:
      branches:
        - main
      tags: ['*']
    pull_request:
    workflow_dispatch:
env:
  JULIA_NUM_THREADS: 2
jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - uses: julia-actions/julia-buildpkg@v1
        with:
          localregistry: https://github.com/abhisrkckl/julia_registry.git
      - name: Install dependencies
        run: |
          julia --project=docs -e '
            import Pkg; Pkg.add(["Documenter", "AbstractTrees"])
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - name: Build & deploy documentation
        run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}