name: pyvela-CI

on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: Test pyvela
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        version:
          - '1.11'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
        with:
          localregistry: https://github.com/abhisrkckl/julia_registry.git
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools pytest pytest-cov pytest-xdist pytest-rerunfailures coverage black emcee nestle h5py 
          pip install git+https://github.com/nanograv/PINT/
          julia -e 'import Pkg; Pkg.develop(path=".")'
          julia -e 'import Pkg; Pkg.add(["Distributions", "DoubleFloats", "BenchmarkTools"])'
          pip install -e .
      - name: Test with pytest
        run: |
          cd pyvela/tests
          pytest --verbose --cov=pyvela -n logical --dist worksteal --reruns 5 .
      - name: Run example notebook
        run: |
          cd ../examples
          jupyter execute vela-demo.ipynb
      - name: Test formatting with black
        run: |
          black --check ..
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.4
        with:
          flag-name: Python